check formatting only

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -37,22 +37,22 @@ jobs:
         with:
           flutter-path: submodules/flutter
 
-      - name: Disable Flutter CLI animations
-        run: flutter config --no-cli-animations
+      # - name: Disable Flutter CLI animations
+      #   run: flutter config --no-cli-animations
 
       - run: flutter pub get
 
       - name: Download Apple fonts
         run: dart run golden_screenshot:download_apple_fonts
 
-      - name: Run tests
-        id: tests
-        run: flutter test --coverage --no-pub --file-reporter=json:test-results.json
+      # - name: Run tests
+      #   id: tests
+      #   run: flutter test --coverage --no-pub --file-reporter=json:test-results.json
 
-      - name: Convert test results to JUnit XML for Codecov
-        run: |
-          flutter pub add dev:junitify
-          dart run junitify -i test-results.json -o test-results.xml
+      # - name: Convert test results to JUnit XML for Codecov
+      #   run: |
+      #     flutter pub add dev:junitify
+      #     dart run junitify -i test-results.json -o test-results.xml
 
       # - name: Upload to Codecov
       #   if: success()
@@ -68,22 +68,23 @@ jobs:
       #     report_type: test_results
       #     files: test-results.xml
 
-      - name: Ensure test failures directory exists
-        if: failure()
-        run: mkdir -p test/failures
+      # - name: Ensure test failures directory exists
+      #   if: failure()
+      #   run: mkdir -p test/failures
 
-      - name: Upload test failures
-        if: failure()
-        uses: actions/upload-artifact@v7
-        with:
-          name: Saber-test-failures
-          path: test/failures
+      # - name: Upload test failures
+      #   if: failure()
+      #   uses: actions/upload-artifact@v7
+      #   with:
+      #     name: Saber-test-failures
+      #     path: test/failures
 
-      - name: Run static analysis
-        run: flutter analyze --no-pub
+      # - name: Run static analysis
+      #   run: flutter analyze --no-pub
 
       - name: Check formatting
         run: |
-          dart format lib packages scripts test --set-exit-if-changed
+          dart format lib packages scripts test --set-exit-if-changed || true
           cat test/custom_directory_selector_android_test.dart
           cat test/custom_directory_selector_foss_test.dart
+          dart format lib packages scripts test --set-exit-if-changed
